# Generated by Django 5.0.2 on 2024-04-07 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_submission_user_alter_submission_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='username',
        ),
    ]
