# Generated by Django 5.0.2 on 2024-04-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_submission_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='subject',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
