# Generated by Django 5.0.2 on 2024-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_submission_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(default='no file', upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='username',
            field=models.CharField(default='anonymous', max_length=100, verbose_name='Username'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
