# Generated by Django 5.0.2 on 2024-04-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_submission_file_remove_submission_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='N/A', max_length=500)),
                ('text', models.CharField(default='N/A', max_length=500)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('admin_response', models.CharField(default='N/A', max_length=500)),
                ('user', models.CharField(default='Anonymous User', max_length=20)),
            ],
        ),
    ]
