# Generated by Django 5.0.2 on 2024-04-18 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_anonymousfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anonymoussubmission'),
        ),
    ]
