# Generated by Django 5.0.2 on 2024-04-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_anonymousfile_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousFile',
        ),
        migrations.DeleteModel(
            name='AnonymousSubmission',
        ),
    ]
